"use client";

import throttle from "lodash.throttle";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import useScrollSpy from "@/hooks/use-scroll-spy";
import { perSlugKey, recordProgress } from "@/lib/reading-store";

import type { ArticleHeading } from "../service";

const MIN_PCT = 0.25; // below this, "resume" isn't worth offering
const MAX_PCT = 0.9; // above this, the reader has effectively finished
const AUTO_DISMISS_MS = 6000;
const PERSIST_THROTTLE_MS = 2000;

interface SavedProgress {
  headingId: string;
  pct: number;
}

function readSaved(slug: string): SavedProgress | null {
  try {
    const raw = localStorage.getItem(perSlugKey(slug));
    if (!raw) {
      return null;
    }
    const parsed = JSON.parse(raw) as Partial<SavedProgress>;
    if (
      typeof parsed.headingId !== "string" ||
      typeof parsed.pct !== "number"
    ) {
      return null;
    }
    return { headingId: parsed.headingId, pct: parsed.pct };
  } catch {
    return null;
  }
}

interface ResumeReadingProps {
  headings: ArticleHeading[];
  slug: string;
}

/**
 * Offers a dismissible "Resume ↓" chip when reopening an article left partway
 * through. Persists the last-passed heading id (not a pixel offset) so the
 * anchor survives the article being regenerated by the wiki importer.
 */
export function ResumeReading({ headings, slug }: ResumeReadingProps) {
  const sectionIds = useMemo(() => headings.map((h) => h.id), [headings]);
  const activeId = useScrollSpy({
    defaultSectionId: sectionIds[0] ?? null,
    sectionIds,
  });
  const activeIdRef = useRef(activeId);
  activeIdRef.current = activeId;

  const [resume, setResume] = useState<SavedProgress | null>(null);

  // Read the saved position once on mount and decide whether to offer resume.
  useEffect(() => {
    if (headings.length < 2) {
      return;
    }
    const saved = readSaved(slug);
    if (!saved || saved.pct < MIN_PCT || saved.pct > MAX_PCT) {
      return;
    }
    if (!document.getElementById(saved.headingId)) {
      return;
    }
    setResume(saved);
    const timer = setTimeout(() => setResume(null), AUTO_DISMISS_MS);
    return () => clearTimeout(timer);
  }, [headings.length, slug]);

  // Persist progress as the reader scrolls (only once actually scrolled, so the
  // saved anchor isn't clobbered with pct≈0 on first paint). Throttled ticks
  // write both the history entry and the per-slug resume state together; a
  // page hide or tab switch flushes the latest position immediately, ahead of
  // the throttle, so it isn't lost to the wider throttle window.
  useEffect(() => {
    const persistNow = () => {
      const scrollable =
        document.documentElement.scrollHeight - window.innerHeight;
      if (scrollable <= 0 || window.scrollY <= 0) {
        return;
      }
      const pct = Math.min(1, Math.max(0, window.scrollY / scrollable));
      // Remember this read on the Shelf once it crosses the resume threshold.
      recordProgress(slug, pct);
      const headingId = activeIdRef.current;
      if (!headingId) {
        return;
      }
      try {
        localStorage.setItem(
          perSlugKey(slug),
          JSON.stringify({ headingId, pct })
        );
      } catch {
        // ignore storage errors (quota / private mode)
      }
    };
    const persist = throttle(persistNow, PERSIST_THROTTLE_MS);
    const flushIfHidden = () => {
      if (document.visibilityState === "hidden") {
        persist.cancel();
        persistNow();
      }
    };

    window.addEventListener("scroll", persist, { passive: true });
    window.addEventListener("pagehide", persistNow);
    document.addEventListener("visibilitychange", flushIfHidden);
    return () => {
      persist.cancel();
      window.removeEventListener("scroll", persist);
      window.removeEventListener("pagehide", persistNow);
      document.removeEventListener("visibilitychange", flushIfHidden);
    };
  }, [slug]);

  const handleResume = useCallback(() => {
    if (resume) {
      document
        .getElementById(resume.headingId)
        ?.scrollIntoView({ behavior: "smooth", block: "start" });
    }
    setResume(null);
  }, [resume]);

  if (!resume) {
    return null;
  }

  return (
    <div className="fixed right-[max(1.25rem,env(safe-area-inset-right))] bottom-[max(1.25rem,env(safe-area-inset-bottom))] z-40 flex items-center gap-1 rounded-full border border-[var(--article-accent,var(--brand))] bg-card px-1 py-1 shadow-paper-lg">
      <button
        className="rounded-full px-3 py-1.5 font-mono text-[11px] text-[var(--article-accent,var(--brand))] uppercase tracking-[0.16em] transition-colors hover:text-foreground"
        onClick={handleResume}
        type="button"
      >
        Resume · {Math.round(resume.pct * 100)}%{" "}
        <span aria-hidden="true">↓</span>
      </button>
      <button
        aria-label="Dismiss resume"
        className="flex size-6 items-center justify-center rounded-full text-foreground-subtle transition-colors hover:text-foreground"
        onClick={() => setResume(null)}
        type="button"
      >
        <span aria-hidden="true">×</span>
      </button>
    </div>
  );
}
