[default]
extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
]

[default.extend-words]
Unparseable = "Unparseable"
PN = "PN"

[files]
extend-exclude = [
  "*.lock",
  "*.snap",
  "CHANGELOG.md",
  "node_modules",
  ".next",
  ".turbo",
  "apps/blog/public/rss",
  "apps/blog/src/content/**",
]
