jobs:
  install:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - save_cache:
          name: Save NPM Package Cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Run type-check
          command: npm run type-check
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run test
          command: npm run test
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Run next build
          command: npm run build
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  conventional-check:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
