version: 2.1

orbs:
  node: circleci/node@5.0.2

aliases:
  - &restore-cache
    restore_cache:
      name: Restore pnpm Package Cache
      keys:
        - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

  - &save-cache
    save_cache:
      name: Save pnpm Package Cache
      paths:
        - node_modules
      key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

  - &install-pnpm
    run:
      name: Install pnpm package manager
      command: sudo npx pnpm add -g pnpm

  - &install-node
    run:
      name: Install dependencies
      command: pnpm install

  - &run-lint
    run:
      name: Run linter
      command: pnpm lint

  - &run-type-check
    run:
      name: Run TypeScript type check
      command: pnpm type-check

  - &run-unit-tests
    run:
      name: Run unit tests
      command: pnpm test

  - &run-build
    run:
      name: Run Build
      command: pnpm build

commands:
  node-build-steps:
    steps:
      - node-install-steps
      - node-test-steps
      - *run-build

  node-install-steps:
    steps:
      - checkout:
          path: ~/howardism
      - *restore-cache
      - *install-pnpm
      - *install-node

  node-test-steps:
    steps:
      - *run-lint
      - *run-type-check
      - *run-unit-tests

jobs:
  build:
    parameters:
      app_name:
        type: string

    docker:
      - image: cimg/node:lts
    working_directory: ~/howardism/apps/<< parameters.app_name >>
    steps:
      - node-build-steps

workflows:
  version: 2
  blog:
    jobs:
      - build:
          app_name: blog
  github:
    jobs:
      - build:
          app_name: github-search
  minecraft:
    jobs:
      - build:
          app_name: minecraft
  recipe:
    jobs:
      - build:
          app_name: recipe
