export const SITE_NAME = "Howardism"
export const TWITTER_USERNAME = "@howard86_"
export const PROFILE_IMAGE_NAME = "profile.jpeg"
export const SITE_DESCRIPTION = "A Software Engineer, Mathematician, and Amateur Diver's Journey"
export const AUTHOR_NAME = "Howard Tai"
export const AUTHOR_EMAIL = "howard@howardism.dev"
