name: Test Applications On Pull Request

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout to ${{ github.event.pull_request.head.ref }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install

      - name: Lint changed apps
        run: bunx turbo run lint

      - name: Check TypeScript definitions
        run: bunx turbo run type-check

      - name: Test changed apps
        run: bunx turbo run test
